### DISCUSSION TITLE
Swap margin for padding on dialog options?

### DISCUSSION THREAD

**Discussion by searls** [josefarias/hotwire_combobox#198] [Ideas]
I noticed that when tapping in the space between options in the mobile dialog would result in deselection and dismissal of the dialog, then learned that this was because `margin-top: 16px` is being set between each option:
![screenshot-2024-08-20-14h38m39s](https://github.com/user-attachments/assets/59dfda3e-2fe5-4bc8-9260-683986ad3d83)

I switched these to padding and that seems to have fixed it:

```css
  .hw-combobox__dialog__listbox li {
    /* Switch margin to padding so taps don't fall through and dismiss the dialog */
    margin-top: 0;
    padding-top: 16px;
  }
```
